---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-clusterrole-namespaces-secrets
  annotations:
    helm.sh/hook: test
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-100"
rules:
- apiGroups: [""]
  resources: ["namespaces", "secrets"]
  verbs: ["create", "get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-clusterrolebinding-namespaces-secrets
  annotations:
    helm.sh/hook: test
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-98"
subjects:
- kind: ServiceAccount
  name: create-tnt-ns
  namespace: {{ .Values.integrationTests.namespace }}
roleRef:
  kind: ClusterRole 
  name: test-clusterrole-namespaces-secrets
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-clusterrole-netpols
  annotations:
    helm.sh/hook: test
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-100"
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["create", "get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-clusterrolebinding-netpols
  annotations:
    helm.sh/hook: test
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-98"
subjects:
- kind: ServiceAccount
  name: create-tnt-ns
  namespace: {{ .Values.integrationTests.namespace }}
roleRef:
  kind: ClusterRole 
  name: test-clusterrole-netpols
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.integrationTests.namespace }}
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-100"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-tnt-ns
  namespace: {{ .Values.integrationTests.namespace }}
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-90"
automountServiceAccountToken: true
