---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-tenant-namespace-wrong-name-failure
  namespace: {{ .Values.integrationTests.namespace }}
  labels:
    purpose: test-pod-tenant-namespace-wrong-name-failure
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-70"
spec:
  serviceAccountName: create-tnt-ns
  automountServiceAccountToken: true
  restartPolicy: Never
  containers:
  - name: test-opa
    image: ubuntu-kubectl
    imagePullPolicy: Never
    command: ["/bin/bash", "-c"]
    args:
      - |
        namespaceName="test-tenant"
        k8sfile="/tmp/test-tenant-ns.yaml"

        echo -n "Creating namespace $namespaceName ... "
        cat <<END > $k8sfile
        apiVersion: v1
        kind: Namespace
        metadata:
          name: $namespaceName
        END

        msg=$(kubectl apply -f $k8sfile --dry-run=server 2>&1)

        # Check whether the policy blocks the request
        if echo "$msg" | grep -q "DENY"; then
          echo "ERROR"

          # It worked as expected, so we exit with status 0
          exit 0
        fi

        echo "OK"
        exit 1


