---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-tenant-netpol-wrong-name-failure
  namespace: {{ .Values.integrationTests.namespace }}
  labels:
    purpose: test-pod-tenant-netpol-wrong-name-failure
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-65"
spec:
  serviceAccountName: create-tnt-ns
  automountServiceAccountToken: true
  restartPolicy: Never
  containers:
  - name: test-opa
    image: ubuntu-kubectl
    imagePullPolicy: Never
    command: ["/bin/bash", "-c"]
    args:
      - |
        nameNetpol="fake-name"
        namespaceDst={{ .Values.integrationTests.namespace }}
        k8sfile="/tmp/test.yaml"

        # Wrong NetworkPolicy name, not allowed
        echo -n "Creating $nameNetpol NetworkPolicy into $namespaceDst namespace ... "
        cat <<END > $k8sfile
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: $nameNetpol
          namespace: $namespaceDst
        spec:
          podSelector: {}
          policyTypes:
          - Ingress
          - Egress
        END

        msg=$(kubectl apply -f $k8sfile --dry-run=server 2>&1)

        # Check whether the policy blocks the request
        if echo "$msg" | grep -q "DENY"; then
          echo "ERROR"

          # It worked as expected, so we exit with status 0
          exit 0
        fi

        echo "OK"
        exit 1
