---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-tenant-secret-wrong-name-failure
  namespace: {{ .Values.integrationTests.namespace }}
  labels:
    purpose: test-pod-tenant-secret-wrong-name-failure
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-65"
spec:
  serviceAccountName: create-tnt-ns
  automountServiceAccountToken: true
  restartPolicy: Never
  containers:
  - name: test-opa
    image: ubuntu-kubectl
    imagePullPolicy: Never
    command: ["/bin/bash", "-c"]
    args:
      - |
        nameSecret="fake-secret"
        namespaceDst={{ .Values.integrationTests.namespace }}
        k8sfile="/tmp/test-tenant-ns.yaml"

        # Wrong Secret name, not allowed
        echo "Creating $nameSecret Secret into $namespaceDst namespace..."
        cat <<END > $k8sfile
        apiVersion: v1
        kind: Secret
        metadata:
          name: $nameSecret
          namespace: $namespaceDst
        type: kubernetes.io/dockercfg
        data:
          .dockercfg: e30= # Empty object {}
        END

        msg=$(kubectl apply -f $k8sfile --dry-run=server 2>&1)

        # Check whether the policy blocks the request
        if echo "$msg" | grep -q "DENY"; then
          echo "ERROR"

          # It worked as expected, so we exit with status 0
          exit 0
        fi

        echo "OK"
        exit 1
